### ISSUE TITLE
The hamburger menu icon is visible when empty

### ISSUE THREAD

**Issue by sanlifer** [Neovici/cosmoz-bottom-bar#27] opened 2018-04-10 11:45 UTC
The hamburger menu is visible in the bottom bar even though it doesn't contain any items.

Where there's only one action such as "comment",  the menu icon should not be displayed. 

 Steps to reproduce

1. Go to /purchase/deviations/invoices/errors/agresso-errors
* Find an invoice with status "waiting booking receipt"
* Click on the menu icon
-->No result (slight color change indicates that the element reacts to the click)

**Comment by sanlifer** [comment] 2018-05-02 12:39
This is still the case:
administration/groups/list-queue#administration-groups-list-queue-tab the hamburger icon is unclickable. If the menu does not contain any items it should not be displayed at all.

**Comment by dotpointer** [comment] 2018-05-02 13:42
Assigning some people on request by sanlifer, first one to take issue can unassign the rest or something :)

**Comment by dotpointer** [comment] 2018-05-02 14:30
For agresso-errors I have tracked it down to cosmoz-bottom-bar. menuElements gets filled with one element:

This is what it is filled with:
<dom-repeat filter="filterSimpleActions" as="action" slot="bottom-bar-menu" tabindex="-1" class="cosmoz-bottom-bar-menu" style="display: none;"><template is="dom-repeat"></template></dom-repeat>

**Comment by JockeCK** [comment] 2018-05-02 15:06
I am thinking(and tested locally) that we could change the row
this._setHasMenuItems(menuElements.length > 0);
into 
this._setHasMenuItems(menuElements.length > 1 || this.hasExtraItems);
hasExtraItems checks for nodes in "extraSlot" which if I understand correctly,
should cover when single button "comment" for example gets hidden in an mobile view. 

not 100% sure though this covers everything, I tested it locally and it worked. But resizing from mobile view into desktop view did require an browser reload to reevaluate the menu(hamburger) button into normal button again.

**Comment by JockeCK** [comment] 2018-05-03 09:36
Actually I have changed my mind after some testing with bottom-bar demo. It worked as it should there far as I could see. 

I now think the real problem is the dom-repeat, Robert posted above. So the problem is in view, not the bottom-bar component. 

Closing this issue and will start a new one in the proper place later.

**Comment by JockeCK** [comment] 2018-05-03 12:10
Pull request # 28 created.

**Comment by JockeCK** [comment] 2018-05-03 13:00
PR #28  merged, should work now. closing

**Comment by JockeCK** [comment] 2018-05-08 13:15
Reopening issue due to there still exists situations where this bug can occur. 

Basically we need to expand the filtering we do on bottom bar node collection.

Created PR #29

**Comment by nomego** [comment] 2018-06-18 10:05
Fixed @JockeCK ?

**Comment by JockeCK** [comment] 2018-11-09 10:40
Whoops, forgot about this one. closing

**Closed by JockeCK** 2018-11-09 10:40 UTC
